# encoding: UTF-8

Country.create([
  {:name=>"Россия", :english_name=>"Russia"},
  {:name=>"Украина", :english_name=>"Ukraine"},
  {:name=>"Беларусь", :english_name=>"Belarus"},
  {:name=>"Казахстан", :english_name=>"Kazakhstan"},
  {:name=>"Азербайджан", :english_name=>"Azerbaijan"},
  {:name=>"Армения", :english_name=>"Armenia"},
  {:name=>"Грузия", :english_name=>"Georgia"},
  {:name=>"Израиль", :english_name=>"Israel"},
  {:name=>"США", :english_name=>"USA"},
  {:name=>"Канада", :english_name=>"Canada"},
  {:name=>"Кыргызстан", :english_name=>"Kyrgyzstan"},
  {:name=>"Латвия", :english_name=>"Latvia"},
  {:name=>"Литва", :english_name=>"Lithuania"},
  {:name=>"Эстония", :english_name=>"Estonia"},
  {:name=>"Молдова", :english_name=>"Moldova"},
  {:name=>"Таджикистан", :english_name=>"Tajikistan"},
  {:name=>"Туркменистан", :english_name=>"Turkmenistan"},
  {:name=>"Узбекистан", :english_name=>"Uzbekistan"},
  {:name=>"Австралия", :english_name=>"Australia"},
  {:name=>"Австрия", :english_name=>"Austria"},
  {:name=>"Албания", :english_name=>"Albania"},
  {:name=>"Алжир", :english_name=>"Algeria"},
  {:name=>"Американское Самоа", :english_name=>"American Samoa"},
  {:name=>"Ангилья", :english_name=>"Anguilla"},
  {:name=>"Ангола", :english_name=>"Angola"},
  {:name=>"Андорра", :english_name=>"Andorra"},
  {:name=>"Антигуа и Барбуда", :english_name=>"Antigua and Barbuda"},
  {:name=>"Аргентина", :english_name=>"Argentina"},
  {:name=>"Аруба", :english_name=>"Aruba"},
  {:name=>"Афганистан", :english_name=>"Afghanistan"},
  {:name=>"Багамы", :english_name=>"Bahamas"},
  {:name=>"Бангладеш", :english_name=>"Bangladesh"},
  {:name=>"Барбадос", :english_name=>"Barbados"},
  {:name=>"Бахрейн", :english_name=>"Bahrain"},
  {:name=>"Белиз", :english_name=>"Belize"},
  {:name=>"Бельгия", :english_name=>"Belgium"},
  {:name=>"Бенин", :english_name=>"Benin"},
  {:name=>"Бермуды", :english_name=>"Bermuda"},
  {:name=>"Болгария", :english_name=>"Bulgaria"},
  {:name=>"Боливия", :english_name=>"Bolivia"},
  {:name=>"Босния и Герцеговина", :english_name=>"Bosnia and Herzegovina"},
  {:name=>"Ботсвана", :english_name=>"Botswana"},
  {:name=>"Бразилия", :english_name=>"Brazil"},
  {:name=>"Бруней-Даруссалам", :english_name=>"Brunei Darussalam"},
  {:name=>"Буркина-Фасо", :english_name=>"Burkina Faso"},
  {:name=>"Бурунди", :english_name=>"Burundi"},
  {:name=>"Бутан", :english_name=>"Bhutan"},
  {:name=>"Вануату", :english_name=>"Vanuatu"},
  {:name=>"Великобритания", :english_name=>"United Kingdom"},
  {:name=>"Венгрия", :english_name=>"Hungary"},
  {:name=>"Венесуэла", :english_name=>"Venezuela"},
  {:name=>"Виргинские острова, Британские", :english_name=>"British Virgin Islands"},
  {:name=>"Виргинские острова, США", :english_name=>"US Virgin Islands"},
  {:name=>"Восточный Тимор", :english_name=>"East Timor"},
  {:name=>"Вьетнам", :english_name=>"Vietnam"},
  {:name=>"Габон", :english_name=>"Gabon"},
  {:name=>"Гаити", :english_name=>"Haiti"},
  {:name=>"Гайана", :english_name=>"Guyana"},
  {:name=>"Гамбия", :english_name=>"Gambia"},
  {:name=>"Гана", :english_name=>"Ghana"},
  {:name=>"Гваделупа", :english_name=>"Guadeloupe"},
  {:name=>"Гватемала", :english_name=>"Guatemala"},
  {:name=>"Гвинея", :english_name=>"Guinea"},
  {:name=>"Гвинея-Бисау", :english_name=>"Guinea-Bissau"},
  {:name=>"Германия", :english_name=>"Germany"},
  {:name=>"Гибралтар", :english_name=>"Gibraltar"},
  {:name=>"Гондурас", :english_name=>"Honduras"},
  {:name=>"Гонконг", :english_name=>"Hong Kong"},
  {:name=>"Гренада", :english_name=>"Grenada"},
  {:name=>"Гренландия", :english_name=>"Greenland"},
  {:name=>"Греция", :english_name=>"Greece"},
  {:name=>"Гуам", :english_name=>"Guam"},
  {:name=>"Дания", :english_name=>"Denmark"},
  {:name=>"Доминика", :english_name=>"Dominica"},
  {:name=>"Доминиканская Республика", :english_name=>"Dominican Republic"},
  {:name=>"Египет", :english_name=>"Egypt"},
  {:name=>"Замбия", :english_name=>"Zambia"},
  {:name=>"Западная Сахара", :english_name=>"Western Sahara"},
  {:name=>"Зимбабве", :english_name=>"Zimbabwe"},
  {:name=>"Индия", :english_name=>"India"},
  {:name=>"Индонезия", :english_name=>"Indonesia"},
  {:name=>"Иордания", :english_name=>"Jordan"},
  {:name=>"Ирак", :english_name=>"Iraq"},
  {:name=>"Иран", :english_name=>"Iran"},
  {:name=>"Ирландия", :english_name=>"Ireland"},
  {:name=>"Исландия", :english_name=>"Iceland"},
  {:name=>"Испания", :english_name=>"Spain"},
  {:name=>"Италия", :english_name=>"Italy"},
  {:name=>"Йемен", :english_name=>"Yemen"},
  {:name=>"Кабо-Верде", :english_name=>"Cape Verde"},
  {:name=>"Камбоджа", :english_name=>"Cambodia"},
  {:name=>"Камерун", :english_name=>"Cameroon"},
  {:name=>"Катар", :english_name=>"Qatar"},
  {:name=>"Кения", :english_name=>"Kenya"},
  {:name=>"Кипр", :english_name=>"Cyprus"},
  {:name=>"Кирибати", :english_name=>"Kiribati"},
  {:name=>"Китай", :english_name=>"China"},
  {:name=>"Колумбия", :english_name=>"Colombia"},
  {:name=>"Коморы", :english_name=>"Comoros"},
  {:name=>"Конго", :english_name=>"Congo"},
  {:name=>"Конго, демократическая республика", :english_name=>"Congo, Democratic Republic"},
  {:name=>"Коста-Рика", :english_name=>"Costa Rica"},
  {:name=>"Кот д`Ивуар", :english_name=>"C&#244;te d`Ivoire"},
  {:name=>"Куба", :english_name=>"Cuba"},
  {:name=>"Кувейт", :english_name=>"Kuwait"},
  {:name=>"Лаос", :english_name=>"Laos"},
  {:name=>"Лесото", :english_name=>"Lesotho"},
  {:name=>"Либерия", :english_name=>"Liberia"},
  {:name=>"Ливан", :english_name=>"Lebanon"},
  {:name=>"Ливия", :english_name=>"Libya"},
  {:name=>"Лихтенштейн", :english_name=>"Liechtenstein"},
  {:name=>"Люксембург", :english_name=>"Luxembourg"},
  {:name=>"Маврикий", :english_name=>"Mauritius"},
  {:name=>"Мавритания", :english_name=>"Mauritania"},
  {:name=>"Мадагаскар", :english_name=>"Madagascar"},
  {:name=>"Макао", :english_name=>"Macau"},
  {:name=>"Македония", :english_name=>"Macedonia"},
  {:name=>"Малави", :english_name=>"Malawi"},
  {:name=>"Малайзия", :english_name=>"Malaysia"},
  {:name=>"Мали", :english_name=>"Mali"},
  {:name=>"Мальдивы", :english_name=>"Maldives"},
  {:name=>"Мальта", :english_name=>"Malta"},
  {:name=>"Марокко", :english_name=>"Morocco"},
  {:name=>"Мартиника", :english_name=>"Martinique"},
  {:name=>"Маршалловы Острова", :english_name=>"Marshall Islands"},
  {:name=>"Мексика", :english_name=>"Mexico"},
  {:name=>"Микронезия, федеративные штаты", :english_name=>"Micronesia"},
  {:name=>"Мозамбик", :english_name=>"Mozambique"},
  {:name=>"Монако", :english_name=>"Monaco"},
  {:name=>"Монголия", :english_name=>"Mongolia"},
  {:name=>"Монтсеррат", :english_name=>"Montserrat"},
  {:name=>"Мьянма", :english_name=>"Myanmar"},
  {:name=>"Намибия", :english_name=>"Namibia"},
  {:name=>"Науру", :english_name=>"Nauru"},
  {:name=>"Непал", :english_name=>"Nepal"},
  {:name=>"Нигер", :english_name=>"Niger"},
  {:name=>"Нигерия", :english_name=>"Nigeria"},
  {:name=>"Кюрасао", :english_name=>"Cura&#231;ao"},
  {:name=>"Нидерланды", :english_name=>"Netherlands"},
  {:name=>"Никарагуа", :english_name=>"Nicaragua"},
  {:name=>"Ниуэ", :english_name=>"Niue"},
  {:name=>"Новая Зеландия", :english_name=>"New Zealand"},
  {:name=>"Новая Каледония", :english_name=>"New Caledonia"},
  {:name=>"Норвегия", :english_name=>"Norway"},
  {:name=>"Объединенные Арабские Эмираты", :english_name=>"United Arab Emirates"},
  {:name=>"Оман", :english_name=>"Oman"},
  {:name=>"Остров Мэн", :english_name=>"Isle of Man"},
  {:name=>"Остров Норфолк", :english_name=>"Norfolk Island"},
  {:name=>"Острова Кайман", :english_name=>"Cayman Islands"},
  {:name=>"Острова Кука", :english_name=>"Cook Islands"},
  {:name=>"Острова Теркс и Кайкос", :english_name=>"Turks and Caicos Islands"},
  {:name=>"Пакистан", :english_name=>"Pakistan"},
  {:name=>"Палау", :english_name=>"Palau"},
  {:name=>"Палестинская автономия", :english_name=>"Palestine"},
  {:name=>"Панама", :english_name=>"Panama"},
  {:name=>"Папуа - Новая Гвинея", :english_name=>"Papua New Guinea"},
  {:name=>"Парагвай", :english_name=>"Paraguay"},
  {:name=>"Перу", :english_name=>"Peru"},
  {:name=>"Питкерн", :english_name=>"Pitcairn Islands"},
  {:name=>"Польша", :english_name=>"Poland"},
  {:name=>"Португалия", :english_name=>"Portugal"},
  {:name=>"Пуэрто-Рико", :english_name=>"Puerto Rico"},
  {:name=>"Реюньон", :english_name=>"R&#233;union"},
  {:name=>"Руанда", :english_name=>"Rwanda"},
  {:name=>"Румыния", :english_name=>"Romania"},
  {:name=>"Сальвадор", :english_name=>"El Salvador"},
  {:name=>"Самоа", :english_name=>"Samoa"},
  {:name=>"Сан-Марино", :english_name=>"San Marino"},
  {:name=>"Сан-Томе и Принсипи", :english_name=>"S&#227;o Tom&#233; and Pr&#237;ncipe"},
  {:name=>"Саудовская Аравия", :english_name=>"Saudi Arabia"},
  {:name=>"Свазиленд", :english_name=>"Swaziland"},
  {:name=>"Святая Елена", :english_name=>"Saint Helena"},
  {:name=>"Северная Корея", :english_name=>"North Korea"},
  {:name=>"Северные Марианские острова", :english_name=>"Northern Mariana Islands"},
  {:name=>"Сейшелы", :english_name=>"Seychelles"},
  {:name=>"Сенегал", :english_name=>"Senegal"},
  {:name=>"Сент-Винсент", :english_name=>"Saint Vincent and the Grenadines"},
  {:name=>"Сент-Китс и Невис", :english_name=>"Saint Kitts and Nevis"},
  {:name=>"Сент-Люсия", :english_name=>"Saint Lucia"},
  {:name=>"Сент-Пьер и Микелон", :english_name=>"Saint Pierre and Miquelon"},
  {:name=>"Сербия", :english_name=>"Serbia"},
  {:name=>"Сингапур", :english_name=>"Singapore"},
  {:name=>"Сирийская Арабская Республика", :english_name=>"Syria"},
  {:name=>"Словакия", :english_name=>"Slovakia"},
  {:name=>"Словения", :english_name=>"Slovenia"},
  {:name=>"Соломоновы Острова", :english_name=>"Solomon Islands"},
  {:name=>"Сомали", :english_name=>"Somalia"},
  {:name=>"Судан", :english_name=>"Sudan"},
  {:name=>"Суринам", :english_name=>"Suriname"},
  {:name=>"Сьерра-Леоне", :english_name=>"Sierra Leone"},
  {:name=>"Таиланд", :english_name=>"Thailand"},
  {:name=>"Тайвань", :english_name=>"Taiwan"},
  {:name=>"Танзания", :english_name=>"Tanzania"},
  {:name=>"Того", :english_name=>"Togo"},
  {:name=>"Токелау", :english_name=>"Tokelau"},
  {:name=>"Тонга", :english_name=>"Tonga"},
  {:name=>"Тринидад и Тобаго", :english_name=>"Trinidad and Tobago"},
  {:name=>"Тувалу", :english_name=>"Tuvalu"},
  {:name=>"Тунис", :english_name=>"Tunisia"},
  {:name=>"Турция", :english_name=>"Turkey"},
  {:name=>"Уганда", :english_name=>"Uganda"},
  {:name=>"Уоллис и Футуна", :english_name=>"Wallis and Futuna"},
  {:name=>"Уругвай", :english_name=>"Uruguay"},
  {:name=>"Фарерские острова", :english_name=>"Faroe Islands"},
  {:name=>"Фиджи", :english_name=>"Fiji"},
  {:name=>"Филиппины", :english_name=>"Philippines"},
  {:name=>"Финляндия", :english_name=>"Finland"},
  {:name=>"Фолклендские острова", :english_name=>"Falkland Islands"},
  {:name=>"Франция", :english_name=>"France"},
  {:name=>"Французская Гвиана", :english_name=>"French Guiana"},
  {:name=>"Французская Полинезия", :english_name=>"French Polynesia"},
  {:name=>"Хорватия", :english_name=>"Croatia"},
  {:name=>"Центрально-Африканская Республика", :english_name=>"Central African Republic"},
  {:name=>"Чад", :english_name=>"Chad"},
  {:name=>"Чехия", :english_name=>"Czech Republic"},
  {:name=>"Чили", :english_name=>"Chile"},
  {:name=>"Швейцария", :english_name=>"Switzerland"},
  {:name=>"Швеция", :english_name=>"Sweden"},
  {:name=>"Шпицберген и Ян Майен", :english_name=>"Svalbard and Jan Mayen"},
  {:name=>"Шри-Ланка", :english_name=>"Sri Lanka"},
  {:name=>"Эквадор", :english_name=>"Ecuador"},
  {:name=>"Экваториальная Гвинея", :english_name=>"Equatorial Guinea"},
  {:name=>"Эритрея", :english_name=>"Eritrea"},
  {:name=>"Эфиопия", :english_name=>"Ethiopia"},
  {:name=>"Южная Корея", :english_name=>"South Korea"},
  {:name=>"Южно-Африканская Республика", :english_name=>"South Africa"},
  {:name=>"Ямайка", :english_name=>"Jamaica"},
  {:name=>"Япония", :english_name=>"Japan"},
  {:name=>"Черногория", :english_name=>"Montenegro"},
  {:name=>"Джибути", :english_name=>"Djibouti"},
  {:name=>"Южный Судан", :english_name=>"South Sudan"},
  {:name=>"Ватикан", :english_name=>"Vatican"},
  {:name=>"Синт-Мартен", :english_name=>"Sint Maarten"},
  {:name=>"Бонайре, Синт-Эстатиус и Саба", :english_name=>"Bonaire, Sint Eustatius and Saba"}
])
